name: Vouchers
main: "${group}.Vouchers"
author: BadBones69
version: ${version}
api-version: 1.13
description: ${description}
website: ${website}

softdepend:
  - PlaceholderAPI

commands:
  vouchers:
    description: Give yourself a Voucher!
    aliases: [voucher]

permissions:
  voucher.admin:
    default: op

  voucher.redeem:
    default: op